loadSprite("grass", "images/grass.png");
loadSprite("portal", "images/portal.png");
loadSprite("s", "images/s.png");
loadSprite("gorilla", "images/gorilla.png");
loadSprite("gorilla", "images/gorilla.png");
loadSprite("JUNGLE", "images/JUNGLE.jpg");
loadSprite("trees", "images/trees.png");
loadSprite("run", "images/run.png");
loadSprite("rain", "images/rain.png");
loadSprite("coin", "images/coin.png");
loadSprite("steel", "images/steel.png");
loadSprite("rock", "images/rock.jpg")
loadSprite("spike", "images/spike.png");
loadSound("junglemp3", "images/junglemp3.mp3");
loadSound("Chill", "images/Chill.mp3");
